apiVersion: batch/v1
kind: Job
metadata:
  name: wine-quality-migrate
  namespace: wine-quality
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: wine-quality-migrate:latest
        envFrom:
          - secretRef: {name: wine-quality-secrets}
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
