apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: wine-quality

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wine-quality-prometheus
rules:
  - apiGroups: [""]
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wine-quality-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: wine-quality
roleRef:
  kind: ClusterRole
  name: wine-quality-prometheus
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: wine-quality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus

      containers:
        - name: prometheus
          image: prom/prometheus:v3.14.0

          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.retention.time=15d

          ports:
            - containerPort: 9090

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

      volumes:
        - name: config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.k8s.yml
                path: prometheus.yml
              - key: alert_rules.yml
                path: alert_rules.yml

        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: wine-quality
spec:
  selector:
    app: prometheus

  ports:
    - port: 9090
      targetPort: 9090
