[build-system]
requires = ["setuptools==83.0.0", "wheel==0.46.2"]
build-backend = "setuptools.build_meta"

[project]
name = "wine-quality-prediction--system"
version = "1.0.0"
description = "End-to-end ML project for wine quality prediction"
readme = "README.md"
requires-python = ">=3.11"

dependencies = []

authors = [
    { name = "Md Arif Aziz", email = "arifaziz0125@gmail.com" }
]

license = { text = "MIT" }

keywords = [
    "mlops",
    "machine-learning",
    "wine-quality",
    "dvc",
    "mlflow",
    "bentoml",
    "kubernetes",
    "docker",
    "aws"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
]

[project.urls]
Homepage = "https://github.com/arifaziz9162/wine-quality-prediction-system"
Repository = "https://github.com/arifaziz9162/wine-quality-prediction-system"
Issues = "https://github.com/arifaziz9162/wine-quality-prediction-system/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["wine_quality_prediction*"]

# -------------
# Black
# -------------

[tool.black]
line-length = 88
target-version = ["py311"]

exclude = '''
/(
    \.git
  | __pycache__
  | artifacts
  | notebooks
  | mlruns
  | logs
  | \.pytest_cache
  | .*\.egg-info
)/
'''

# -------------
# Ruff
# -------------

[tool.ruff]
line-length = 88
target-version = "py311"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "artifacts",
    "notebooks",
    "mlruns",
    "logs",
    "*.egg-info"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "W",
    "UP",
    "B"
]

ignore = [
    "E501"
]

# -------------
# Pytest
# -------------

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-ra -q"

# -------------
# Coverage
# -------------

[tool.coverage.run]
source = ["src", "serving"]
omit = ["*/__init__.py"]
[tool.coverage.report]
show_missing = true
skip_covered = true
